<?php
/**
 * Dossier
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Dossier Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Dossier implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Dossier';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'nom' => 'string',
        'gabarit' => 'string',
        'metadonnees' => '\OpenAPI\Client\Model\Metadonnee[]',
        'indexation_demandee_le' => '\DateTime',
        'indexe_le' => '\DateTime',
        'cree_le' => '\DateTime',
        'cree_par' => '\OpenAPI\Client\Model\DossierCreePar',
        'mis_a_jour_le' => '\DateTime',
        'filtres_acces' => '\OpenAPI\Client\Model\DossierFiltresAccesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'nom' => null,
        'gabarit' => 'uuid',
        'metadonnees' => null,
        'indexation_demandee_le' => 'date-time',
        'indexe_le' => 'date-time',
        'cree_le' => 'date-time',
        'cree_par' => null,
        'mis_a_jour_le' => 'date-time',
        'filtres_acces' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'nom' => false,
		'gabarit' => false,
		'metadonnees' => false,
		'indexation_demandee_le' => true,
		'indexe_le' => true,
		'cree_le' => false,
		'cree_par' => true,
		'mis_a_jour_le' => true,
		'filtres_acces' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'nom' => 'nom',
        'gabarit' => 'gabarit',
        'metadonnees' => 'metadonnees',
        'indexation_demandee_le' => 'indexationDemandeeLe',
        'indexe_le' => 'indexeLe',
        'cree_le' => 'creeLe',
        'cree_par' => 'creePar',
        'mis_a_jour_le' => 'misAJourLe',
        'filtres_acces' => 'filtresAcces'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'nom' => 'setNom',
        'gabarit' => 'setGabarit',
        'metadonnees' => 'setMetadonnees',
        'indexation_demandee_le' => 'setIndexationDemandeeLe',
        'indexe_le' => 'setIndexeLe',
        'cree_le' => 'setCreeLe',
        'cree_par' => 'setCreePar',
        'mis_a_jour_le' => 'setMisAJourLe',
        'filtres_acces' => 'setFiltresAcces'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'nom' => 'getNom',
        'gabarit' => 'getGabarit',
        'metadonnees' => 'getMetadonnees',
        'indexation_demandee_le' => 'getIndexationDemandeeLe',
        'indexe_le' => 'getIndexeLe',
        'cree_le' => 'getCreeLe',
        'cree_par' => 'getCreePar',
        'mis_a_jour_le' => 'getMisAJourLe',
        'filtres_acces' => 'getFiltresAcces'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('nom', $data ?? [], null);
        $this->setIfExists('gabarit', $data ?? [], null);
        $this->setIfExists('metadonnees', $data ?? [], null);
        $this->setIfExists('indexation_demandee_le', $data ?? [], null);
        $this->setIfExists('indexe_le', $data ?? [], null);
        $this->setIfExists('cree_le', $data ?? [], null);
        $this->setIfExists('cree_par', $data ?? [], null);
        $this->setIfExists('mis_a_jour_le', $data ?? [], null);
        $this->setIfExists('filtres_acces', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if ($this->container['gabarit'] === null) {
            $invalidProperties[] = "'gabarit' can't be null";
        }
        if ($this->container['metadonnees'] === null) {
            $invalidProperties[] = "'metadonnees' can't be null";
        }
        if ($this->container['indexation_demandee_le'] === null) {
            $invalidProperties[] = "'indexation_demandee_le' can't be null";
        }
        if ($this->container['indexe_le'] === null) {
            $invalidProperties[] = "'indexe_le' can't be null";
        }
        if ($this->container['cree_le'] === null) {
            $invalidProperties[] = "'cree_le' can't be null";
        }
        if ($this->container['cree_par'] === null) {
            $invalidProperties[] = "'cree_par' can't be null";
        }
        if ($this->container['mis_a_jour_le'] === null) {
            $invalidProperties[] = "'mis_a_jour_le' can't be null";
        }
        if ($this->container['filtres_acces'] === null) {
            $invalidProperties[] = "'filtres_acces' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return self
     */
    public function setNom($nom)
    {

        if (is_null($nom)) {
            throw new \InvalidArgumentException('non-nullable nom cannot be null');
        }

        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets gabarit
     *
     * @return string
     */
    public function getGabarit()
    {
        return $this->container['gabarit'];
    }

    /**
     * Sets gabarit
     *
     * @param string $gabarit gabarit
     *
     * @return self
     */
    public function setGabarit($gabarit)
    {

        if (is_null($gabarit)) {
            throw new \InvalidArgumentException('non-nullable gabarit cannot be null');
        }

        $this->container['gabarit'] = $gabarit;

        return $this;
    }

    /**
     * Gets metadonnees
     *
     * @return \OpenAPI\Client\Model\Metadonnee[]
     */
    public function getMetadonnees()
    {
        return $this->container['metadonnees'];
    }

    /**
     * Sets metadonnees
     *
     * @param \OpenAPI\Client\Model\Metadonnee[] $metadonnees metadonnees
     *
     * @return self
     */
    public function setMetadonnees($metadonnees)
    {

        if (is_null($metadonnees)) {
            throw new \InvalidArgumentException('non-nullable metadonnees cannot be null');
        }

        $this->container['metadonnees'] = $metadonnees;

        return $this;
    }

    /**
     * Gets indexation_demandee_le
     *
     * @return \DateTime
     */
    public function getIndexationDemandeeLe()
    {
        return $this->container['indexation_demandee_le'];
    }

    /**
     * Sets indexation_demandee_le
     *
     * @param \DateTime $indexation_demandee_le indexation_demandee_le
     *
     * @return self
     */
    public function setIndexationDemandeeLe($indexation_demandee_le)
    {

        if (is_null($indexation_demandee_le)) {
            array_push($this->openAPINullablesSetToNull, 'indexation_demandee_le');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('indexation_demandee_le', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['indexation_demandee_le'] = $indexation_demandee_le;

        return $this;
    }

    /**
     * Gets indexe_le
     *
     * @return \DateTime
     */
    public function getIndexeLe()
    {
        return $this->container['indexe_le'];
    }

    /**
     * Sets indexe_le
     *
     * @param \DateTime $indexe_le indexe_le
     *
     * @return self
     */
    public function setIndexeLe($indexe_le)
    {

        if (is_null($indexe_le)) {
            array_push($this->openAPINullablesSetToNull, 'indexe_le');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('indexe_le', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['indexe_le'] = $indexe_le;

        return $this;
    }

    /**
     * Gets cree_le
     *
     * @return \DateTime
     */
    public function getCreeLe()
    {
        return $this->container['cree_le'];
    }

    /**
     * Sets cree_le
     *
     * @param \DateTime $cree_le cree_le
     *
     * @return self
     */
    public function setCreeLe($cree_le)
    {

        if (is_null($cree_le)) {
            throw new \InvalidArgumentException('non-nullable cree_le cannot be null');
        }

        $this->container['cree_le'] = $cree_le;

        return $this;
    }

    /**
     * Gets cree_par
     *
     * @return \OpenAPI\Client\Model\DossierCreePar
     */
    public function getCreePar()
    {
        return $this->container['cree_par'];
    }

    /**
     * Sets cree_par
     *
     * @param \OpenAPI\Client\Model\DossierCreePar $cree_par cree_par
     *
     * @return self
     */
    public function setCreePar($cree_par)
    {

        if (is_null($cree_par)) {
            array_push($this->openAPINullablesSetToNull, 'cree_par');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cree_par', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['cree_par'] = $cree_par;

        return $this;
    }

    /**
     * Gets mis_a_jour_le
     *
     * @return \DateTime
     */
    public function getMisAJourLe()
    {
        return $this->container['mis_a_jour_le'];
    }

    /**
     * Sets mis_a_jour_le
     *
     * @param \DateTime $mis_a_jour_le mis_a_jour_le
     *
     * @return self
     */
    public function setMisAJourLe($mis_a_jour_le)
    {

        if (is_null($mis_a_jour_le)) {
            array_push($this->openAPINullablesSetToNull, 'mis_a_jour_le');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mis_a_jour_le', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['mis_a_jour_le'] = $mis_a_jour_le;

        return $this;
    }

    /**
     * Gets filtres_acces
     *
     * @return \OpenAPI\Client\Model\DossierFiltresAccesInner[]
     */
    public function getFiltresAcces()
    {
        return $this->container['filtres_acces'];
    }

    /**
     * Sets filtres_acces
     *
     * @param \OpenAPI\Client\Model\DossierFiltresAccesInner[] $filtres_acces filtres_acces
     *
     * @return self
     */
    public function setFiltresAcces($filtres_acces)
    {

        if (is_null($filtres_acces)) {
            throw new \InvalidArgumentException('non-nullable filtres_acces cannot be null');
        }

        $this->container['filtres_acces'] = $filtres_acces;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


