<?php
/**
 * InputGabaritDeDocumentMetadonneesInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InputGabaritDeDocumentMetadonneesInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InputGabaritDeDocumentMetadonneesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InputGabaritDeDocument_metadonnees_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'format' => '\OpenAPI\Client\Model\MetadonneeFormat',
        'libelle' => 'string',
        'aide' => 'string',
        'obligatoire' => 'bool',
        'valeurs' => '\OpenAPI\Client\Model\InputGabaritDeDocumentMetadonneesInnerValeursInner[]',
        'choix_multiple' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'format' => null,
        'libelle' => null,
        'aide' => null,
        'obligatoire' => null,
        'valeurs' => null,
        'choix_multiple' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'format' => false,
		'libelle' => false,
		'aide' => false,
		'obligatoire' => false,
		'valeurs' => false,
		'choix_multiple' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'format' => 'format',
        'libelle' => 'libelle',
        'aide' => 'aide',
        'obligatoire' => 'obligatoire',
        'valeurs' => 'valeurs',
        'choix_multiple' => 'choixMultiple'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'format' => 'setFormat',
        'libelle' => 'setLibelle',
        'aide' => 'setAide',
        'obligatoire' => 'setObligatoire',
        'valeurs' => 'setValeurs',
        'choix_multiple' => 'setChoixMultiple'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'format' => 'getFormat',
        'libelle' => 'getLibelle',
        'aide' => 'getAide',
        'obligatoire' => 'getObligatoire',
        'valeurs' => 'getValeurs',
        'choix_multiple' => 'getChoixMultiple'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('format', $data ?? [], null);
        $this->setIfExists('libelle', $data ?? [], null);
        $this->setIfExists('aide', $data ?? [], null);
        $this->setIfExists('obligatoire', $data ?? [], null);
        $this->setIfExists('valeurs', $data ?? [], null);
        $this->setIfExists('choix_multiple', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['format'] === null) {
            $invalidProperties[] = "'format' can't be null";
        }
        if ($this->container['libelle'] === null) {
            $invalidProperties[] = "'libelle' can't be null";
        }
        if ($this->container['aide'] === null) {
            $invalidProperties[] = "'aide' can't be null";
        }
        if ($this->container['obligatoire'] === null) {
            $invalidProperties[] = "'obligatoire' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets format
     *
     * @return \OpenAPI\Client\Model\MetadonneeFormat
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param \OpenAPI\Client\Model\MetadonneeFormat $format format
     *
     * @return self
     */
    public function setFormat($format)
    {

        if (is_null($format)) {
            throw new \InvalidArgumentException('non-nullable format cannot be null');
        }

        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets libelle
     *
     * @return string
     */
    public function getLibelle()
    {
        return $this->container['libelle'];
    }

    /**
     * Sets libelle
     *
     * @param string $libelle libelle
     *
     * @return self
     */
    public function setLibelle($libelle)
    {

        if (is_null($libelle)) {
            throw new \InvalidArgumentException('non-nullable libelle cannot be null');
        }

        $this->container['libelle'] = $libelle;

        return $this;
    }

    /**
     * Gets aide
     *
     * @return string
     */
    public function getAide()
    {
        return $this->container['aide'];
    }

    /**
     * Sets aide
     *
     * @param string $aide aide
     *
     * @return self
     */
    public function setAide($aide)
    {

        if (is_null($aide)) {
            throw new \InvalidArgumentException('non-nullable aide cannot be null');
        }

        $this->container['aide'] = $aide;

        return $this;
    }

    /**
     * Gets obligatoire
     *
     * @return bool
     */
    public function getObligatoire()
    {
        return $this->container['obligatoire'];
    }

    /**
     * Sets obligatoire
     *
     * @param bool $obligatoire obligatoire
     *
     * @return self
     */
    public function setObligatoire($obligatoire)
    {

        if (is_null($obligatoire)) {
            throw new \InvalidArgumentException('non-nullable obligatoire cannot be null');
        }

        $this->container['obligatoire'] = $obligatoire;

        return $this;
    }

    /**
     * Gets valeurs
     *
     * @return \OpenAPI\Client\Model\InputGabaritDeDocumentMetadonneesInnerValeursInner[]|null
     */
    public function getValeurs()
    {
        return $this->container['valeurs'];
    }

    /**
     * Sets valeurs
     *
     * @param \OpenAPI\Client\Model\InputGabaritDeDocumentMetadonneesInnerValeursInner[]|null $valeurs Cette clé n'est nécessaire que pour le format `enum`
     *
     * @return self
     */
    public function setValeurs($valeurs)
    {

        if (is_null($valeurs)) {
            throw new \InvalidArgumentException('non-nullable valeurs cannot be null');
        }

        $this->container['valeurs'] = $valeurs;

        return $this;
    }

    /**
     * Gets choix_multiple
     *
     * @return bool|null
     */
    public function getChoixMultiple()
    {
        return $this->container['choix_multiple'];
    }

    /**
     * Sets choix_multiple
     *
     * @param bool|null $choix_multiple Cette clé ne s'applique que pour le format `enum`
     *
     * @return self
     */
    public function setChoixMultiple($choix_multiple)
    {

        if (is_null($choix_multiple)) {
            throw new \InvalidArgumentException('non-nullable choix_multiple cannot be null');
        }

        $this->container['choix_multiple'] = $choix_multiple;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


