<?php
/**
 * MesHabilitations
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MesHabilitations Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MesHabilitations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MesHabilitations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'gabarits_de_dossier' => '\OpenAPI\Client\Model\MesHabilitationsGabaritsDeDossierInner[]',
        'gabarits_de_document' => '\OpenAPI\Client\Model\MesHabilitationsGabaritsDeDocumentInner[]',
        'bannettes' => '\OpenAPI\Client\Model\MesHabilitationsBannettesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'gabarits_de_dossier' => null,
        'gabarits_de_document' => null,
        'bannettes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'gabarits_de_dossier' => false,
		'gabarits_de_document' => false,
		'bannettes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'gabarits_de_dossier' => 'gabaritsDeDossier',
        'gabarits_de_document' => 'gabaritsDeDocument',
        'bannettes' => 'bannettes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'gabarits_de_dossier' => 'setGabaritsDeDossier',
        'gabarits_de_document' => 'setGabaritsDeDocument',
        'bannettes' => 'setBannettes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'gabarits_de_dossier' => 'getGabaritsDeDossier',
        'gabarits_de_document' => 'getGabaritsDeDocument',
        'bannettes' => 'getBannettes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('gabarits_de_dossier', $data ?? [], null);
        $this->setIfExists('gabarits_de_document', $data ?? [], null);
        $this->setIfExists('bannettes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['gabarits_de_dossier'] === null) {
            $invalidProperties[] = "'gabarits_de_dossier' can't be null";
        }
        if ($this->container['gabarits_de_document'] === null) {
            $invalidProperties[] = "'gabarits_de_document' can't be null";
        }
        if ($this->container['bannettes'] === null) {
            $invalidProperties[] = "'bannettes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets gabarits_de_dossier
     *
     * @return \OpenAPI\Client\Model\MesHabilitationsGabaritsDeDossierInner[]
     */
    public function getGabaritsDeDossier()
    {
        return $this->container['gabarits_de_dossier'];
    }

    /**
     * Sets gabarits_de_dossier
     *
     * @param \OpenAPI\Client\Model\MesHabilitationsGabaritsDeDossierInner[] $gabarits_de_dossier gabarits_de_dossier
     *
     * @return self
     */
    public function setGabaritsDeDossier($gabarits_de_dossier)
    {

        if (is_null($gabarits_de_dossier)) {
            throw new \InvalidArgumentException('non-nullable gabarits_de_dossier cannot be null');
        }

        $this->container['gabarits_de_dossier'] = $gabarits_de_dossier;

        return $this;
    }

    /**
     * Gets gabarits_de_document
     *
     * @return \OpenAPI\Client\Model\MesHabilitationsGabaritsDeDocumentInner[]
     */
    public function getGabaritsDeDocument()
    {
        return $this->container['gabarits_de_document'];
    }

    /**
     * Sets gabarits_de_document
     *
     * @param \OpenAPI\Client\Model\MesHabilitationsGabaritsDeDocumentInner[] $gabarits_de_document gabarits_de_document
     *
     * @return self
     */
    public function setGabaritsDeDocument($gabarits_de_document)
    {

        if (is_null($gabarits_de_document)) {
            throw new \InvalidArgumentException('non-nullable gabarits_de_document cannot be null');
        }

        $this->container['gabarits_de_document'] = $gabarits_de_document;

        return $this;
    }

    /**
     * Gets bannettes
     *
     * @return \OpenAPI\Client\Model\MesHabilitationsBannettesInner[]
     */
    public function getBannettes()
    {
        return $this->container['bannettes'];
    }

    /**
     * Sets bannettes
     *
     * @param \OpenAPI\Client\Model\MesHabilitationsBannettesInner[] $bannettes bannettes
     *
     * @return self
     */
    public function setBannettes($bannettes)
    {

        if (is_null($bannettes)) {
            throw new \InvalidArgumentException('non-nullable bannettes cannot be null');
        }

        $this->container['bannettes'] = $bannettes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


