<?php
/**
 * ModifierProcessusRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModifierProcessusRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModifierProcessusRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'modifierProcessus_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nom' => 'string',
        'nom_technique_workey' => 'string',
        'nom_document_workey' => 'string',
        'nom_role_workey' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nom' => null,
        'nom_technique_workey' => null,
        'nom_document_workey' => null,
        'nom_role_workey' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nom' => false,
		'nom_technique_workey' => false,
		'nom_document_workey' => false,
		'nom_role_workey' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nom' => 'nom',
        'nom_technique_workey' => 'nomTechniqueWorkey',
        'nom_document_workey' => 'nomDocumentWorkey',
        'nom_role_workey' => 'nomRoleWorkey'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nom' => 'setNom',
        'nom_technique_workey' => 'setNomTechniqueWorkey',
        'nom_document_workey' => 'setNomDocumentWorkey',
        'nom_role_workey' => 'setNomRoleWorkey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nom' => 'getNom',
        'nom_technique_workey' => 'getNomTechniqueWorkey',
        'nom_document_workey' => 'getNomDocumentWorkey',
        'nom_role_workey' => 'getNomRoleWorkey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('nom', $data ?? [], null);
        $this->setIfExists('nom_technique_workey', $data ?? [], null);
        $this->setIfExists('nom_document_workey', $data ?? [], null);
        $this->setIfExists('nom_role_workey', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if ($this->container['nom_technique_workey'] === null) {
            $invalidProperties[] = "'nom_technique_workey' can't be null";
        }
        if ($this->container['nom_document_workey'] === null) {
            $invalidProperties[] = "'nom_document_workey' can't be null";
        }
        if ($this->container['nom_role_workey'] === null) {
            $invalidProperties[] = "'nom_role_workey' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return self
     */
    public function setNom($nom)
    {

        if (is_null($nom)) {
            throw new \InvalidArgumentException('non-nullable nom cannot be null');
        }

        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets nom_technique_workey
     *
     * @return string
     */
    public function getNomTechniqueWorkey()
    {
        return $this->container['nom_technique_workey'];
    }

    /**
     * Sets nom_technique_workey
     *
     * @param string $nom_technique_workey nom_technique_workey
     *
     * @return self
     */
    public function setNomTechniqueWorkey($nom_technique_workey)
    {

        if (is_null($nom_technique_workey)) {
            throw new \InvalidArgumentException('non-nullable nom_technique_workey cannot be null');
        }

        $this->container['nom_technique_workey'] = $nom_technique_workey;

        return $this;
    }

    /**
     * Gets nom_document_workey
     *
     * @return string
     */
    public function getNomDocumentWorkey()
    {
        return $this->container['nom_document_workey'];
    }

    /**
     * Sets nom_document_workey
     *
     * @param string $nom_document_workey nom_document_workey
     *
     * @return self
     */
    public function setNomDocumentWorkey($nom_document_workey)
    {

        if (is_null($nom_document_workey)) {
            throw new \InvalidArgumentException('non-nullable nom_document_workey cannot be null');
        }

        $this->container['nom_document_workey'] = $nom_document_workey;

        return $this;
    }

    /**
     * Gets nom_role_workey
     *
     * @return string
     */
    public function getNomRoleWorkey()
    {
        return $this->container['nom_role_workey'];
    }

    /**
     * Sets nom_role_workey
     *
     * @param string $nom_role_workey nom_role_workey
     *
     * @return self
     */
    public function setNomRoleWorkey($nom_role_workey)
    {

        if (is_null($nom_role_workey)) {
            throw new \InvalidArgumentException('non-nullable nom_role_workey cannot be null');
        }

        $this->container['nom_role_workey'] = $nom_role_workey;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


