<?php
/**
 * ReponseEtatLdapConfiguration
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ReponseEtatLdapConfiguration Class Doc Comment
 *
 * @category Class
 * @description Si le ldap n&#39;est pas configuré alors cette clé n&#39;est pas retournée
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReponseEtatLdapConfiguration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReponseEtatLdap_configuration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dsn' => 'string',
        'dn' => 'string',
        'dn_liste_utilisateurs' => 'string',
        'attributs' => '\OpenAPI\Client\Model\ReponseEtatLdapConfigurationAttributs',
        'joignable' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dsn' => null,
        'dn' => null,
        'dn_liste_utilisateurs' => null,
        'attributs' => null,
        'joignable' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dsn' => false,
		'dn' => false,
		'dn_liste_utilisateurs' => false,
		'attributs' => false,
		'joignable' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dsn' => 'dsn',
        'dn' => 'dn',
        'dn_liste_utilisateurs' => 'dnListeUtilisateurs',
        'attributs' => 'attributs',
        'joignable' => 'joignable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dsn' => 'setDsn',
        'dn' => 'setDn',
        'dn_liste_utilisateurs' => 'setDnListeUtilisateurs',
        'attributs' => 'setAttributs',
        'joignable' => 'setJoignable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dsn' => 'getDsn',
        'dn' => 'getDn',
        'dn_liste_utilisateurs' => 'getDnListeUtilisateurs',
        'attributs' => 'getAttributs',
        'joignable' => 'getJoignable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('dsn', $data ?? [], null);
        $this->setIfExists('dn', $data ?? [], null);
        $this->setIfExists('dn_liste_utilisateurs', $data ?? [], null);
        $this->setIfExists('attributs', $data ?? [], null);
        $this->setIfExists('joignable', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dsn'] === null) {
            $invalidProperties[] = "'dsn' can't be null";
        }
        if ($this->container['dn'] === null) {
            $invalidProperties[] = "'dn' can't be null";
        }
        if ($this->container['dn_liste_utilisateurs'] === null) {
            $invalidProperties[] = "'dn_liste_utilisateurs' can't be null";
        }
        if ($this->container['attributs'] === null) {
            $invalidProperties[] = "'attributs' can't be null";
        }
        if ($this->container['joignable'] === null) {
            $invalidProperties[] = "'joignable' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dsn
     *
     * @return string
     */
    public function getDsn()
    {
        return $this->container['dsn'];
    }

    /**
     * Sets dsn
     *
     * @param string $dsn L'url qui permet de se connecter au ldap
     *
     * @return self
     */
    public function setDsn($dsn)
    {

        if (is_null($dsn)) {
            throw new \InvalidArgumentException('non-nullable dsn cannot be null');
        }

        $this->container['dsn'] = $dsn;

        return $this;
    }

    /**
     * Gets dn
     *
     * @return string
     */
    public function getDn()
    {
        return $this->container['dn'];
    }

    /**
     * Sets dn
     *
     * @param string $dn Nom permettant de se connecter au ldap pour lister les utilisateurs
     *
     * @return self
     */
    public function setDn($dn)
    {

        if (is_null($dn)) {
            throw new \InvalidArgumentException('non-nullable dn cannot be null');
        }

        $this->container['dn'] = $dn;

        return $this;
    }

    /**
     * Gets dn_liste_utilisateurs
     *
     * @return string
     */
    public function getDnListeUtilisateurs()
    {
        return $this->container['dn_liste_utilisateurs'];
    }

    /**
     * Sets dn_liste_utilisateurs
     *
     * @param string $dn_liste_utilisateurs DN utilisé pour rechercher tous les utilisateurs du ldap
     *
     * @return self
     */
    public function setDnListeUtilisateurs($dn_liste_utilisateurs)
    {

        if (is_null($dn_liste_utilisateurs)) {
            throw new \InvalidArgumentException('non-nullable dn_liste_utilisateurs cannot be null');
        }

        $this->container['dn_liste_utilisateurs'] = $dn_liste_utilisateurs;

        return $this;
    }

    /**
     * Gets attributs
     *
     * @return \OpenAPI\Client\Model\ReponseEtatLdapConfigurationAttributs
     */
    public function getAttributs()
    {
        return $this->container['attributs'];
    }

    /**
     * Sets attributs
     *
     * @param \OpenAPI\Client\Model\ReponseEtatLdapConfigurationAttributs $attributs attributs
     *
     * @return self
     */
    public function setAttributs($attributs)
    {

        if (is_null($attributs)) {
            throw new \InvalidArgumentException('non-nullable attributs cannot be null');
        }

        $this->container['attributs'] = $attributs;

        return $this;
    }

    /**
     * Gets joignable
     *
     * @return bool
     */
    public function getJoignable()
    {
        return $this->container['joignable'];
    }

    /**
     * Sets joignable
     *
     * @param bool $joignable Si l'application arrive à se connecter au ldap
     *
     * @return self
     */
    public function setJoignable($joignable)
    {

        if (is_null($joignable)) {
            throw new \InvalidArgumentException('non-nullable joignable cannot be null');
        }

        $this->container['joignable'] = $joignable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


