<?php
/**
 * ResultatRecherche
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ResultatRecherche Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResultatRecherche implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResultatRecherche';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'nom' => 'string',
        'media_type' => 'string',
        'gabarit' => '\OpenAPI\Client\Model\ResultatRechercheGabarit',
        'armoire' => '\OpenAPI\Client\Model\ResultatRechercheArmoire',
        'bannette' => '\OpenAPI\Client\Model\ResultatRechercheBannette',
        'dossier' => '\OpenAPI\Client\Model\ResultatRechercheDossier',
        'metadonnees' => '\OpenAPI\Client\Model\ResultatRechercheMetadonneesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'nom' => null,
        'media_type' => null,
        'gabarit' => null,
        'armoire' => null,
        'bannette' => null,
        'dossier' => null,
        'metadonnees' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'nom' => false,
		'media_type' => false,
		'gabarit' => false,
		'armoire' => false,
		'bannette' => false,
		'dossier' => false,
		'metadonnees' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'nom' => 'nom',
        'media_type' => 'mediaType',
        'gabarit' => 'gabarit',
        'armoire' => 'armoire',
        'bannette' => 'bannette',
        'dossier' => 'dossier',
        'metadonnees' => 'metadonnees'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'nom' => 'setNom',
        'media_type' => 'setMediaType',
        'gabarit' => 'setGabarit',
        'armoire' => 'setArmoire',
        'bannette' => 'setBannette',
        'dossier' => 'setDossier',
        'metadonnees' => 'setMetadonnees'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'nom' => 'getNom',
        'media_type' => 'getMediaType',
        'gabarit' => 'getGabarit',
        'armoire' => 'getArmoire',
        'bannette' => 'getBannette',
        'dossier' => 'getDossier',
        'metadonnees' => 'getMetadonnees'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('nom', $data ?? [], null);
        $this->setIfExists('media_type', $data ?? [], null);
        $this->setIfExists('gabarit', $data ?? [], null);
        $this->setIfExists('armoire', $data ?? [], null);
        $this->setIfExists('bannette', $data ?? [], null);
        $this->setIfExists('dossier', $data ?? [], null);
        $this->setIfExists('metadonnees', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if ($this->container['media_type'] === null) {
            $invalidProperties[] = "'media_type' can't be null";
        }
        if ($this->container['metadonnees'] === null) {
            $invalidProperties[] = "'metadonnees' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return self
     */
    public function setNom($nom)
    {

        if (is_null($nom)) {
            throw new \InvalidArgumentException('non-nullable nom cannot be null');
        }

        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets media_type
     *
     * @return string
     */
    public function getMediaType()
    {
        return $this->container['media_type'];
    }

    /**
     * Sets media_type
     *
     * @param string $media_type media_type
     *
     * @return self
     */
    public function setMediaType($media_type)
    {

        if (is_null($media_type)) {
            throw new \InvalidArgumentException('non-nullable media_type cannot be null');
        }

        $this->container['media_type'] = $media_type;

        return $this;
    }

    /**
     * Gets gabarit
     *
     * @return \OpenAPI\Client\Model\ResultatRechercheGabarit|null
     */
    public function getGabarit()
    {
        return $this->container['gabarit'];
    }

    /**
     * Sets gabarit
     *
     * @param \OpenAPI\Client\Model\ResultatRechercheGabarit|null $gabarit gabarit
     *
     * @return self
     */
    public function setGabarit($gabarit)
    {

        if (is_null($gabarit)) {
            throw new \InvalidArgumentException('non-nullable gabarit cannot be null');
        }

        $this->container['gabarit'] = $gabarit;

        return $this;
    }

    /**
     * Gets armoire
     *
     * @return \OpenAPI\Client\Model\ResultatRechercheArmoire|null
     */
    public function getArmoire()
    {
        return $this->container['armoire'];
    }

    /**
     * Sets armoire
     *
     * @param \OpenAPI\Client\Model\ResultatRechercheArmoire|null $armoire armoire
     *
     * @return self
     */
    public function setArmoire($armoire)
    {

        if (is_null($armoire)) {
            throw new \InvalidArgumentException('non-nullable armoire cannot be null');
        }

        $this->container['armoire'] = $armoire;

        return $this;
    }

    /**
     * Gets bannette
     *
     * @return \OpenAPI\Client\Model\ResultatRechercheBannette|null
     */
    public function getBannette()
    {
        return $this->container['bannette'];
    }

    /**
     * Sets bannette
     *
     * @param \OpenAPI\Client\Model\ResultatRechercheBannette|null $bannette bannette
     *
     * @return self
     */
    public function setBannette($bannette)
    {

        if (is_null($bannette)) {
            throw new \InvalidArgumentException('non-nullable bannette cannot be null');
        }

        $this->container['bannette'] = $bannette;

        return $this;
    }

    /**
     * Gets dossier
     *
     * @return \OpenAPI\Client\Model\ResultatRechercheDossier|null
     */
    public function getDossier()
    {
        return $this->container['dossier'];
    }

    /**
     * Sets dossier
     *
     * @param \OpenAPI\Client\Model\ResultatRechercheDossier|null $dossier dossier
     *
     * @return self
     */
    public function setDossier($dossier)
    {

        if (is_null($dossier)) {
            throw new \InvalidArgumentException('non-nullable dossier cannot be null');
        }

        $this->container['dossier'] = $dossier;

        return $this;
    }

    /**
     * Gets metadonnees
     *
     * @return \OpenAPI\Client\Model\ResultatRechercheMetadonneesInner[]
     */
    public function getMetadonnees()
    {
        return $this->container['metadonnees'];
    }

    /**
     * Sets metadonnees
     *
     * @param \OpenAPI\Client\Model\ResultatRechercheMetadonneesInner[] $metadonnees metadonnees
     *
     * @return self
     */
    public function setMetadonnees($metadonnees)
    {

        if (is_null($metadonnees)) {
            throw new \InvalidArgumentException('non-nullable metadonnees cannot be null');
        }

        $this->container['metadonnees'] = $metadonnees;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


