<?php
/**
 * ParametresGabaritDocumentGroupementTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ParametresGabaritDocumentGroupementTest Class Doc Comment
 *
 * @category    Class
 * @description L&#39;absence de cette section désactive le groupement. Il est possible de grouper sur les formats &#x60;date&#x60;, &#x60;bool&#x60; et &#x60;enum&#x60;
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParametresGabaritDocumentGroupementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ParametresGabaritDocumentGroupement"
     */
    public function testParametresGabaritDocumentGroupement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metadonnee"
     */
    public function testPropertyMetadonnee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "periode"
     */
    public function testPropertyPeriode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
