<?php
/**
 * BannetteApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BannetteApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BannetteApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activerRechercheDansContenuPourUneBannette
     *
     * Activer/désactiver la recherche dans le contenu des documents d'une bannette.
     *
     */
    public function testActiverRechercheDansContenuPourUneBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bannettes
     *
     * Lister les bannettes.
     *
     */
    public function testBannettes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerBannette
     *
     * Créer une bannette.
     *
     */
    public function testCreerBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deplacerDocumentBannette
     *
     * Déplacer un document non classé dans une autre bannette.
     *
     */
    public function testDeplacerDocumentBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsBannette
     *
     * Lister les documents présents dans la bannette.
     *
     */
    public function testDocumentsBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierBannette
     *
     * Mise à jour de la bannette.
     *
     */
    public function testModifierBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerBannette
     *
     * Supprimer une bannette.
     *
     */
    public function testSupprimerBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploaderDocument
     *
     * Créer un document dans une bannette.
     *
     */
    public function testUploaderDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
