<?php
/**
 * CategoriesDeGabaritsDeDocumentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CategoriesDeGabaritsDeDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CategoriesDeGabaritsDeDocumentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for creerCategorieGabaritDocument
     *
     * Créer une catégorie de gabarits de document dans un gabarit de dossier.
     *
     */
    public function testCreerCategorieGabaritDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerGabaritDocumentCategorie
     *
     * Créer un gabarit de document dans une catégorie.
     *
     */
    public function testCreerGabaritDocumentCategorie()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renommerCategorieGabaritDocument
     *
     * Renommer une catégorie de gabarits de document.
     *
     */
    public function testRenommerCategorieGabaritDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerCategorieGabaritDocument
     *
     * Supprimer une catégorie de gabarits de document.
     *
     */
    public function testSupprimerCategorieGabaritDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
