<?php
/**
 * DocumentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for binaire
     *
     * Récupération du flux de données binaires liées au document.
     *
     */
    public function testBinaire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for binaireVersion
     *
     * Récupération du flux de données binaires liées au document.
     *
     */
    public function testBinaireVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for classerDirectement
     *
     * Créer un document directement classé.
     *
     */
    public function testClasserDirectement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for classerDocument
     *
     * Classer un document dans un gabarit donné.
     *
     */
    public function testClasserDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deplacerDocumentBannette
     *
     * Déplacer un document non classé dans une autre bannette.
     *
     */
    public function testDeplacerDocumentBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deverrouillerDocument
     *
     * Déverrouiller un document.
     *
     */
    public function testDeverrouillerDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for document
     *
     * Récupérer un document.
     *
     */
    public function testDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documents
     *
     * Lister les documents classés dans ce gabarit.
     *
     */
    public function testDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsBannette
     *
     * Lister les documents présents dans la bannette.
     *
     */
    public function testDocumentsBannette()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsDossier
     *
     * Lister les documents d'un dossier.
     *
     */
    public function testDocumentsDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for lancerProcessusDocument
     *
     * Lancer un processus pour un document.
     *
     */
    public function testLancerProcessusDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierMetadonneesDocument
     *
     * Modifier les métadonnées d'un document.
     *
     */
    public function testModifierMetadonneesDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for preClasser
     *
     * Pré-classer un document dans un gabarit donné.
     *
     */
    public function testPreClasser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for previsualiserDocument
     *
     * Récupération des données binaires permettant de prévisualiser le document dans le navigateur web.
     *
     */
    public function testPrevisualiserDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rechercheDocuments
     *
     * Recherche de documents.
     *
     */
    public function testRechercheDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rechercheRapideDocuments
     *
     * Recherche rapide de documents.
     *
     */
    public function testRechercheRapideDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for remplacerBinaire
     *
     * Remplacer le binaire d'un document.
     *
     */
    public function testRemplacerBinaire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restaurerVersion
     *
     * Restaurer le document à cette version du binaire.
     *
     */
    public function testRestaurerVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerDocument
     *
     * Supprimer un document.
     *
     */
    public function testSupprimerDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploaderDocument
     *
     * Créer un document dans une bannette.
     *
     */
    public function testUploaderDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verrouillerDocument
     *
     * Verrouiller un document.
     *
     */
    public function testVerrouillerDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
