<?php
/**
 * DossierApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DossierApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DossierApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for creerDossier
     *
     * Créer un nouveau dossier.
     *
     */
    public function testCreerDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsDossier
     *
     * Lister les documents d'un dossier.
     *
     */
    public function testDocumentsDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dossier
     *
     * Récupérer un dossier.
     *
     */
    public function testDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listerContenuCibleParLiensDuDossier
     *
     * Liste tous les contenus ciblés par des liens d'un dossier.
     *
     */
    public function testListerContenuCibleParLiensDuDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listerDossiers
     *
     * Lister les dossiers existants pour ce gabarit de dossier.
     *
     */
    public function testListerDossiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierMetadonneesDossier
     *
     * Modifier les métadonnées d'un dossier.
     *
     */
    public function testModifierMetadonneesDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rechercheDossiers
     *
     * Recherche de dossiers.
     *
     */
    public function testRechercheDossiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rechercheRapideDossiers
     *
     * Recherche rapide de dossiers.
     *
     */
    public function testRechercheRapideDossiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for selectionnerFiltreAccesDossier
     *
     * Sélectionner une valeur de filtre d'accès pour un dossier.
     *
     */
    public function testSelectionnerFiltreAccesDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerDossier
     *
     * Supprimer un dossier.
     *
     */
    public function testSupprimerDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
