<?php
/**
 * FiltresAccesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FiltresAccesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FiltresAccesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ajouterValeurFiltreAcces
     *
     * Ajouter une valeur à un filtre d'accès.
     *
     */
    public function testAjouterValeurFiltreAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerFiltreAcces
     *
     * Créer un filtre d'accès.
     *
     */
    public function testCreerFiltreAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for desactiverValeurFiltreAcces
     *
     * Désactiver une valeur d'un filtre d'accès.
     *
     */
    public function testDesactiverValeurFiltreAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for filtresAcces
     *
     * Lister les filtres d'accès.
     *
     */
    public function testFiltresAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for filtresAccesUtilisateurs
     *
     * Lister les utilisateurs pouvant être sélectionnés dans un filtre d'accès.
     *
     */
    public function testFiltresAccesUtilisateurs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renommerFiltreAcces
     *
     * Renommer un filtre d'accès.
     *
     */
    public function testRenommerFiltreAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renommerValeurFiltreAcces
     *
     * Renommer une valeur d'un filtre d'accès.
     *
     */
    public function testRenommerValeurFiltreAcces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for selectionnerFiltresAccesUtilisateur
     *
     * Sélectionner une valeur d'un filtre d'accès à un utilisateur.
     *
     */
    public function testSelectionnerFiltresAccesUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerFiltre
     *
     * Suppression d'un filtre d'accès.
     *
     */
    public function testSupprimerFiltre()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
