<?php
/**
 * GabaritDeDossierApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GabaritDeDossierApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GabaritDeDossierApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ajouterMetadonneeGabaritDossier
     *
     * Ajout d'une nouvelle métadonnée au gabarit de dossier.
     *
     */
    public function testAjouterMetadonneeGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for associerFiltreAccesGabaritDeDossier
     *
     * Associer un filtre d'accès à un gabarit de dossier.
     *
     */
    public function testAssocierFiltreAccesGabaritDeDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerCategorieGabaritDocument
     *
     * Créer une catégorie de gabarits de document dans un gabarit de dossier.
     *
     */
    public function testCreerCategorieGabaritDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerDossier
     *
     * Créer un nouveau dossier.
     *
     */
    public function testCreerDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerGabaritDocumentGabaritDossier
     *
     * Créer un gabarit de document dans un gabarit de dossier.
     *
     */
    public function testCreerGabaritDocumentGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerGabaritDossierArmoire
     *
     * Créer un gabarit de dossier dans une armoire.
     *
     */
    public function testCreerGabaritDossierArmoire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerLienGabaritDossier
     *
     * Création d'un lien vers un autre gabarit de dossier.
     *
     */
    public function testCreerLienGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dissocierFiltreAccesGabaritDeDossier
     *
     * Dissocier un filtre d'accès d'un gabarit de dossier.
     *
     */
    public function testDissocierFiltreAccesGabaritDeDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gabaritDossier
     *
     * Récupération d'un gabarit de dossier.
     *
     */
    public function testGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listerDossiers
     *
     * Lister les dossiers existants pour ce gabarit de dossier.
     *
     */
    public function testListerDossiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listerGabaritsDocumentGabaritDossier
     *
     * Lister les gabarits de document d'un gabarit de dossier.
     *
     */
    public function testListerGabaritsDocumentGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listerGabaritsDossierArmoire
     *
     * Lister les gabarits de dossier d'une armoire.
     *
     */
    public function testListerGabaritsDossierArmoire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierLienGabaritDossier
     *
     * Modifier un lien vers un gabarit de dossier.
     *
     */
    public function testModifierLienGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierMetadonneeGabaritDossier
     *
     * Modification d'une métadonnée d'un gabarit de dossier.
     *
     */
    public function testModifierMetadonneeGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierModeleNomDynamiqueGabaritDossier
     *
     * Modifier le modèle de nom dynamique d'un gabarit de dossier.
     *
     */
    public function testModifierModeleNomDynamiqueGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renommerGabaritDossier
     *
     * Renommer un gabarit de dossier.
     *
     */
    public function testRenommerGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerGabaritDossier
     *
     * Supprimer un gabarit de dossier.
     *
     */
    public function testSupprimerGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerLienGabaritDossier
     *
     * Supprimer un lien vers un gabarit de dossier.
     *
     */
    public function testSupprimerLienGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerMetadonneeGabaritDossier
     *
     * Suppression d'une métadonnée d'un gabarit de dossier.
     *
     */
    public function testSupprimerMetadonneeGabaritDossier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
