<?php
/**
 * UtilisateursApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX
 *
 * MultiGest version 10
 *
 * The version of the OpenAPI document: canari-11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UtilisateursApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UtilisateursApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activerUtilisateur
     *
     * Activation et désactivation d'un utilisateur.
     *
     */
    public function testActiverUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for creerUtilisateur
     *
     * Créer un utilisateur.
     *
     */
    public function testCreerUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for habilitationsUtilisateurConnecte
     *
     * Récupérer les habilitations de l'utilisateur connecté.
     *
     */
    public function testHabilitationsUtilisateurConnecte()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierMotDePasse
     *
     * Modifier le mot de passe d'un utilisateur.
     *
     */
    public function testModifierMotDePasse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifierUtilisateur
     *
     * Modification d'un utilisateur.
     *
     */
    public function testModifierUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for selectionnerFiltresAccesUtilisateur
     *
     * Sélectionner une valeur d'un filtre d'accès à un utilisateur.
     *
     */
    public function testSelectionnerFiltresAccesUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for supprimerUtilisateur
     *
     * Suppression d'un utilisateur.
     *
     */
    public function testSupprimerUtilisateur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for utilisateurs
     *
     * Lister les utilisateurs.
     *
     */
    public function testUtilisateurs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
